name: OpenAI API Workflow
on:
  push:
    branches:
      - main
jobs:
  generate-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
      - name: Generate text
        run: |
          python app.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_SECRET }}
